/** Verbatim from a 30-day inbox sample, 2026-08-27. Senders and subjects only. */
export const SAMPLE = [
["hello@edikted.com","GET 10% OFF EVERYTHING YOU WANTED"],
["Hacker_Dojo@user.luma-mail.com","New message in Veteran Innovation Hackathon"],
["noreply-accounts@google.com","You shared some Google Account data with Amazon Web Services"],
["notifications@builder.aws.com","Your Skill Builder access is ready"],
["hello@edikted.com","Welcome Laksh, Open For 10% OFF EVERYTHING"],
["notifications@github.com","Re: [lgoyal6/modern-renaissance-artifacts] Keep submission files in a folder of their own (08cffde)"],
["notifications@github.com","Re: [lgoyal6/modern-renaissance-artifacts] Keep submission files in a folder of their own (PR #11)"],
["notifications@github.com","Re: [lgoyal6/modern-renaissance-artifacts] Include rejected submissions in the Drive copy (24e21e1)"],
["notifications@github.com","Re: [lgoyal6/modern-renaissance-artifacts] Include rejected submissions in the Drive copy (PR #10)"],
["aws-cs-mfa-form@support.aws.com","RE:[CASE 178777897600089] [AWS MFA Support Form Submission]"],
["inbox@hiringevents.coreweave.com","See you TONIGHT! CoreWeave Sunnyvale Networking Event"],
["disney@myworkday.com","Thank You for Your Interest - Glendale System Software Engineering Internship, Spring 2027"],
["mackenzie.ball@pitt.edu","PNC Interview Opportunity for SteelHacks Registrants!"],
["no-reply@us.greenhouse-mail.io","Thank you for your interest in Verkada, Laksh"],
["directconsideration@mail.beehiiv.com","Direct Consideration #003"],
["noreply@qualcomm.com","Your Qualcomm Candidate Profile - Tell Us How to Stay in Touch"],
["wayne@convex.dev","Your Firecrawl code for the All Gas Hackathon"],
["Customer_Service_IN@swarovski.com","CGB03021411 - Doubt regarding order #10IN00000287919"],
["itsajchan@user.luma-mail.com","You are invited to Vibe Code like a Professional - Product Landing Pages"],
["support@hackerrankforwork.com","Thanks for taking the Millennium 2027 Global ENG and AI Intern Test"],
["usr-RiZj97uJ321yhOI@user.luma-mail.com","You are invited to Punk Software Hack Night: LLM Freemaxxing"],
["no-reply@us.greenhouse-mail.io","Thank you for applying to Verkada"],
["notifications@github.com","Re: [drfinancialai/intern-ai-projects] refactor(screening): one owner of which status is dispositive (PR #53)"],
["daishi@contactdoublecheck.com","Appointment booked: 30 min with Daishi (CEO @ DoubleCheck Legal)"],
["convex@calendar.luma-mail.com","Registration confirmed for Convex All Gas Hackathon"],
["wayne_convex@user.luma-mail.com","You are invited to Convex All Gas Hackathon"],
["experts@updates.rustlabs.ai","Your rustLabs account is still here"],
["disney@myworkday.com","Thank You for Your Interest - WDW Computer Science / Computer Engineering Interns, Spring 2027"],
["noreply@pypi.org","[PyPI] Email verification"],
["cdr@yardi.com","YES Utility Billing New E-Statement Available #Ref#4124"],
["store+56409555118@t.shopifyemail.com","Order 1ML67811 confirmed"],
["payment-report@payu.in","Your Order at One magnolia lane is successful"],
["bgarfinkel@stellic.com","Re: Stellic - pathfinders challenge submission"],
["noreply@getvfairs.com","Your registration is confirmed for IEEE Global Career Fair 2026"],
["support@hackerrankforwork.com","Millennium 2027 Global ENG and AI Intern Test Invitation to complete the Millennium Management Assessment"],
["no-reply@optiver.com","Your login code to the optiver assessment portal"],
["no-reply@optiver.us","Take the Next Step in your Optiver Application"],
["systemmessage@paycomonline.com","Your AI Software Engineering Intern Application"],
["donotreply@msg.paycomonline.com","UNION HOME MORTGAGE Password setup"],
["no-reply@us.greenhouse-mail.io","Thank you for applying to SK hynix memory solutions America Inc."],
["no-reply@us.greenhouse-mail.io","Security code for your application to SK hynix memory solutions America Inc."],
["jobs@experis.com","Application Next Steps: Python Developer"],
["customer_service_in@swarovski.com","Your order 10IN00000287919 is on its way"],
["noreply@aiven.io","Welcome to Aiven!"],
["noreply@github.com","[GitHub] A third-party OAuth application has been added to your account"],
["customer_service_in@swarovski.com","Your order 10IN00000287919 is confirmed"],
["rewards@reward.tremendous.com","Your prepaid card transaction failed"],
].map(([from, subject]) => ({ from, subject, snippet: "" }));
